#pragma once

#include <gloomy/gl.hpp>
#include <gloomy/GL/Raw/Enum.hpp>

namespace gloomy {
	enum class BufferKind : gloomy::Enum {
		ARRAY_BUFFER = gl::ARRAY_BUFFER,
		ATOMIC_COUNTER_BUFFER = gl::ATOMIC_COUNTER_BUFFER,
		COPY_READ_BUFFER = gl::COPY_READ_BUFFER,
		COPY_WRITE_BUFFER = gl::COPY_WRITE_BUFFER,
		DISPATCH_INDIRECT_BUFFER = gl::DISPATCH_INDIRECT_BUFFER,
		DRAW_INDIRECT_BUFFER = gl::DRAW_INDIRECT_BUFFER,
		ELEMENT_ARRAY_BUFFER = gl::ELEMENT_ARRAY_BUFFER,
		PIXEL_PACK_BUFFER = gl::PIXEL_PACK_BUFFER,
		PIXEL_UNPACK_BUFFER = gl::PIXEL_UNPACK_BUFFER,
		QUERY_BUFFER = gl::QUERY_BUFFER,
		SHADER_STORAGE_BUFFER = gl::SHADER_STORAGE_BUFFER,
		TEXTURE_BUFFER = gl::TEXTURE_BUFFER,
		TRANSFORM_FEEDBACK_BUFFER = gl::TRANSFORM_FEEDBACK_BUFFER,
		UNIFORM_BUFFER = gl::UNIFORM_BUFFER
	};
}