image:
  - Visual Studio 2017
before_build:
- cmd: >-
    git submodule update --init --recursive

    cmake -H. -B./build -G "Visual Studio 15" -D GLOOMY_DEBUG:BOOL=TRUE -D GLOOMY_EXAMPLES:BOOL=TRUE
build:
  project: build/gloomy_all.sln